### ISSUE TITLE
Search tab

### ISSUE THREAD

**Issue by olesyash** [olesyash/Find_Your_Friends#5]
- [x] On search tab, location of the friend will be updated every constant period of time and place
- [x] Stop button will stop the communication, play will resume it 
- [x] Long press on floating button will ask the user if he want to cancel the search
- [x] After user cancel the search, any new search( even the same person) will ask again for approval !

**Comment by ItamarShDev** [comment]
its has decided that long clicking the FAB will stop the search (without user confirmation)
normal click will pause the search
